---
reviews:
  high_level_summary: true
engines:
  duplication:
    include:
      - "src/**/*"
    exclude_paths:
      - "src/abis/**/*"
      - "tests/**/*"
      - ".sonarlint/**/*"
      - ".github/**/*"
      - "diagrams/**/*"
      - "scripts/**/*"

exclude_paths:
  - "src/abis/**/*"
  - "tests/**/*"
  - ".sonarlint/**/*"
  - ".github/**/*"
  - "diagrams/**/*"
  - "vitest.config.ts"
  - "scripts/**/*"
include_paths:
  - "tests/integration/**/*"
